services:
    web_server:
      build: .
#      ports:
#        - "8000:5000"
    nginx_server:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      ports:
        - "7000:80"
      depends_on:
        - web_server